/* ──────────────────────────────────────────────────────────────────────────
   learnroman-daten.js — DER LEARNROMAN (fester Inhalt, kein API-Call).
   Root-Helfer wie haeppchen-db.js / wortschatz.js / sprichwort.js.
   KEIN vercel.json-Eintrag (statische Datei, keine Function).

     window.spikiuLearnroman(zielsprache, muttersprache) → Buch | null

   Ein Buch:
     { buch, zielsprache, muttersprache, titel,
       etappen:[{id,nm}, …],                       // Anzeigenamen in der MUTTERSPRACHE
       kapitel:[{level, n, title, teaser, body:[…]}] }

   Block-Typen im body (Schlüssel SPRACHNEUTRAL — nie de:/es:, weil Deutsch mal
   Ziel- und mal Muttersprache ist):
     {na:'…'}          Erzählung in der MUTTERSPRACHE (Regie, Innensicht) · kein Audio
     {z:'…', tr:'…'}   ZIELSPRACHE, eine Zeile/ein Zug · tr optional (Brücke) · 🔊
     {p:'…'}           fließende ZIELSPRACH-Prosa (nur Etappe Anwendung) · kein tr · 🔊

   Heute zwei Bücher; en/el fehlen und werden schlicht nicht angezeigt (null),
   statt Platzhalter zu erfinden. Sprache ist ein FELD, kein Datei-Schnitt —
   ein drittes Buch ist ein weiterer Eintrag in BUECHER, sonst nichts.

   Der Text stammt 1:1 aus den abgenommenen Prototypen
   proto-learnroman-lukas.html / proto-learnroman-marta.html (Design 05.08.,
   Leo). Nicht umformulieren, nicht kürzen, nicht ergänzen.
   ────────────────────────────────────────────────────────────────────────── */
(function (w) {
  if (w.spikiuLearnroman) return;

  // ── Etappen: IDs sind kanonisch und fest, die ANZEIGENAMEN sind lokalisiert
  //    (Auftrag 05.08. §5 — für eine Madrilenin sind drei deutsche Wörter an der
  //    wichtigsten Stelle des Bildschirms eine Mauer, kein Wegweiser). ──
  var ETAPPEN_IDS = ['fundament', 'aufbau', 'anwendung'];
  var ETAPPEN_NAMEN = {
    de: { fundament: 'Fundament',   aufbau: 'Aufbau',      anwendung: 'Anwendung' },
    es: { fundament: 'Fundamentos', aufbau: 'Ampliación',  anwendung: 'En práctica' },
    // en: VORSCHLAG aus dem Auftrag, von Leo noch NICHT bestätigt. Greift erst,
    // wenn es ein Buch mit muttersprache 'en' gibt — heute gibt es keins.
    en: { fundament: 'Foundations', aufbau: 'Building up', anwendung: 'In practice' }
  };
  function etappenFuer(mutter) {
    var n = ETAPPEN_NAMEN[mutter] || ETAPPEN_NAMEN.de;
    return ETAPPEN_IDS.map(function (id) { return { id: id, nm: n[id] }; });
  }

  // ══ BUCH 1 · „Lukas in Madrid" — Zielsprache es, Muttersprache de ══════════
  // Ziel-Anteil je Kapitel: 30 / 40 / 43 / 100 % (gemessen, Auftrag §3).
  var LUKAS = [
 {level:'fundament',n:1,title:'El aeropuerto',teaser:'Lukas landet in Madrid — und ein Taxifahrer nennt ihn alemán.',body:[
   {na:'Dienstag, drei Uhr nachmittags. Das Flugzeug landet in Madrid-Barajas. Lukas sitzt am Fenster: viel Sonne, gelbliches Gras, kein einziges Wölkchen. Hamburg war heute früh grau.'},
   {na:'Die Leute klatschen. Lukas dreht den Kopf. Klatschen die wirklich? Im Flugzeug? Eine ältere Frau neben ihm lacht.'},
   {z:'Bienvenido a España. ¿Es tu primera vez aquí?',tr:'Willkommen in Spanien. Ist es dein erstes Mal hier?'},
   {z:'Sí. Mi primera vez.'},
   {z:'Madrid es una ciudad muy amable. Te va a gustar.',tr:'Madrid ist eine sehr freundliche Stadt. Sie wird dir gefallen.'},
   {z:'Gracias.'},
   {na:'Das Wort kommt heraus, ohne dass er nachdenken muss. Gutes Zeichen.'},
   {na:'Im Terminal: Stimmen, Lautsprecher, Koffer auf Rollen. Band Nummer 12. Ein Koffer kommt. Nicht seiner. Noch einer. Wo ist meiner?'},
   {na:'Dann — endlich — ein großer roter Koffer. Am Anhänger steht: Lukas Hoffmann. Hamburgo, Alemania. Sein Vater hatte ihn ausgefüllt. Auf Spanisch sogar.'},
   {na:'Draußen: eine Reihe Taxis. Ein Mann mit grauem Haar und Sonnenbrille schaut ihn an.'},
   {z:'Hola, buenas tardes. ¿A dónde vamos?',tr:'Hallo, guten Tag. Wohin fahren wir?'},
   {z:'Calle del Tribulete, número 18. Lavapiés.'},
   {z:'Muy bien. Suba, por favor. ¿La maleta roja es suya?',tr:'Steigen Sie ein, bitte. Ist der rote Koffer Ihrer?'},
   {z:'Sí, es mía. Es muy grande.',tr:'Ja, er ist meiner. Er ist sehr groß.'},
   {z:'Grande y roja. Así no se pierde.',tr:'Groß und rot. So geht er nicht verloren.'},
   {na:'Sie fahren los. Madrid zum ersten Mal: lange Straßen, gelbe Häuser, ein riesiges Stierplakat. Wie im Klischee. Aber echt.'},
   {z:'¿De dónde eres?',tr:'Woher kommst du?'},
   {z:'De Alemania. De Hamburgo.'},
   {z:'¡Ah, Alemania! ¿Te gusta el fútbol?',tr:'Magst du Fußball?'},
   {z:'Un poco.'},
   {z:'Bayern München. Muy buen equipo. Muy fuerte.',tr:'Sehr gute Mannschaft. Sehr stark.'},
   {z:'Sí, sí. Bayern.'},
   {na:'Ja sagen ist einfacher als erklären. Der Fahrer redet weiter. Schnell. Lukas versteht einzelne Wörter — calor, barrio, verano — den Rest hört er wie Musik.'},
   {na:'Vierzig Minuten später hält das Taxi an.'},
   {z:'Ya hemos llegado. Son veintiocho euros con cincuenta.',tr:'Wir sind da. Es sind 28,50 Euro.'},
   {na:'Lukas zahlt mit einem Fünfzig-Euro-Schein.'},
   {z:'Aquí tiene el cambio. Bienvenido a Madrid, alemán.',tr:'Hier ist Ihr Wechselgeld. Willkommen, Deutscher.'},
   {na:'Alemán. Zum ersten Mal nennt ihn jemand so. Es klingt nicht hart — fast wie ein Spitzname.'},
   {na:'Eine alte braune Tür, Nummer 18. Daneben viele Klingeln. Lukas sucht den Namen von María: Sánchez Vega — 4º derecha. Er atmet tief ein. Und drückt.'},
   {z:'¿Sí?'},
   {z:'Hola... soy Lukas.'},
   {z:'¡¡¡Lukas!!! ¡Por fin! Sube, sube. Cuarto piso, a la derecha.',tr:'Endlich! Komm hoch. Vierter Stock, rechts.'},
   {na:'Vier Stockwerke ohne Aufzug. Stufe für Stufe. Das Hemd klebt am Rücken. Mein erstes spanisches Workout.'},
   {na:'Oben steht die Tür offen. Eine junge Frau mit kurzen schwarzen Haaren und einem Lächeln, als hätte sie den ganzen Tag gewartet.'},
   {z:'¡Bienvenido, Lukas! Pasa, pasa. ¿Estás bien?',tr:'Komm rein. Geht es dir gut?'},
   {z:'Sí. Estoy bien. Estoy muy cansado.',tr:'Ich bin sehr müde.'},
   {z:'Normal. Cuatro pisos sin ascensor, con maleta. Ven, te enseño la casa.',tr:'Vier Stockwerke ohne Aufzug. Komm, ich zeige dir die Wohnung.'},
   {z:'Gracias, María.'},
   {z:'Aquí no se dice gracias. Esta es tu casa ahora.',tr:'Hier sagt man nicht danke. Das ist jetzt dein Zuhause.'},
   {z:'¿Tienes hambre? Hay pan, hay queso, hay tomate.',tr:'Hast du Hunger? Es gibt Brot, Käse, Tomaten.'},
   {z:'Sí. Tengo mucha hambre.',tr:'Ja. Ich habe großen Hunger.'},
   {z:'Perfecto. Primero la maleta, luego la cena.',tr:'Perfekt. Erst der Koffer, dann das Abendessen.'},
   {na:'Lukas stellt den Koffer ab. Enger Flur, Bilder, ein Fahrrad neben der Tür.'},
   {na:'Er ist angekommen. Wirklich angekommen.'}]},
 {level:'fundament',n:2,title:'Mi nuevo piso',teaser:'Zwei Mitbewohner, eine Tortilla — und das Wort hostia.',body:[
   {na:'Drinnen riecht es nach Knoblauch. Nach echtem Essen — etwas, das jemand gerade kocht.'},
   {na:'María nimmt ihm den roten Koffer ab.'},
   {z:'¡Qué pesada! ¿Has traído piedras de Hamburgo?',tr:'Wie schwer! Hast du Steine aus Hamburg mitgebracht?'},
   {z:'Casi. Libros.',tr:'Fast. Bücher.'},
   {z:'¡Un alemán con libros! Mi madre va a estar contenta.',tr:'Meine Mutter wird sich freuen.'},
   {z:'Vale.'},
   {na:'Vale. Ein Wort, das er heute zum dritten Mal hört. Es scheint alles zu bedeuten.'},
   {z:'El pasillo es estrecho. Hay fotos en blanco y negro y un mapa de España.',tr:'Der Flur ist eng. Es gibt schwarz-weiße Fotos und eine Karte von Spanien.'},
   {z:'Aquí está la cocina. Aquí el baño. Y aquí el salón.'},
   {na:'An der Pfanne steht ein Mann. Lockige Haare, altes Bandshirt. Er dreht sich um und schreit fast:'},
   {z:'¡QUIIIILLO! ¿Cómo va eso? Tú eres el alemán, ¿no?',tr:'Heeey! Wie läuft es? Du bist der Deutsche, oder?'},
   {na:'Quillo? Was ist quillo? Aber er versteht alemán und nickt.'},
   {z:'Sí. Soy Lukas.'},
   {z:'¡Pablo! Andaluz, de Sevilla. Encantadísimo.'},
   {na:'Pablo drückt ihm die Hand. Wirklich stark. In Deutschland drücken wir nicht so. Mental notiert.'},
   {z:'Estoy haciendo una tortilla. ¿Tienes hambre?',tr:'Ich mache gerade eine Tortilla. Hast du Hunger?'},
   {z:'Sí, mucha.'},
   {na:'Mucha, nicht mucho. Hunger ist auf Spanisch weiblich. Kleiner Triumph.'},
   {z:'¿Te gusta con cebolla o sin cebolla?',tr:'Magst du sie mit oder ohne Zwiebel?'},
   {z:'No lo sé. Nunca la he probado.',tr:'Ich weiß nicht. Ich habe sie noch nie probiert.'},
   {z:'¿Nunca? ¡Hostia! Pues hoy empieza tu vida.',tr:'Nie? Mensch! Dann fängt heute dein Leben an.'},
   {z:'Aquí está tu habitación.',tr:'Hier ist dein Zimmer.'},
   {na:'Klein. Ein Bett, ein Schreibtisch, ein Schrank, der nicht ganz schließt. Das Fenster geht auf einen Innenhof — gegenüber schläft eine Katze auf der Fensterbank.'},
   {z:'Ese es Goyo. El gato de los vecinos. Está siempre allí.',tr:'Das ist Goyo. Die Katze der Nachbarn. Er ist immer dort.'},
   {z:'¿Goyo?'},
   {z:'Sí, como Goya, el pintor. Los vecinos son artistas.',tr:'Ja, wie Goya, der Maler. Die Nachbarn sind Künstler.'},
   {na:'Eine Katze namens Goya. Madrid.'},
   {z:'En el salón hay una mujer en el sofá. Lee un libro.',tr:'Im Wohnzimmer sitzt eine Frau auf dem Sofa. Sie liest ein Buch.'},
   {na:'Kurze blonde Haare, eine zu große Brille.'},
   {z:'Hola. Tú eres Lukas, ¿verdad? Yo soy Carmen.',tr:'Hallo. Du bist Lukas, oder? Ich bin Carmen.'},
   {z:'Sí. Mucho gusto.'},
   {z:'¿Y qué tal el viaje? ¿Muy largo?',tr:'Und wie war die Reise? Sehr lang?'},
   {z:'Tres horas. Pero con la maleta, muy largo.',tr:'Drei Stunden. Aber mit dem Koffer sehr lang.'},
   {z:'Carmen es así. No habla mucho, pero escucha todo.',tr:'Carmen ist so. Sie spricht wenig, aber hört alles.'},
   {z:'¡La cena está lista! ¡A la mesa!'},
   {z:'La tortilla está en la mesa: dorada, gruesa, un poco quemada.',tr:'Die Tortilla steht auf dem Tisch: golden, dick, ein bisschen verbrannt.'},
   {z:'Hay pan, vino y cuatro vasos.',tr:'Es gibt Brot, Wein und vier Gläser.'},
   {z:'Por Lukas. Bienvenido a la casa.',tr:'Auf Lukas. Willkommen im Haus.'},
   {na:'Sie stoßen an. In Hamburg schaut man sich dabei in die Augen. Hier auch — aber länger.'},
   {z:'¿Te gusta?'},
   {z:'Muchísimo.',tr:'Sehr.'},
   {z:'¡Hostia, qué bien! La tortilla de mi madre es mejor, pero la mía no está mal.',tr:'Die Tortilla meiner Mutter ist besser, aber meine ist auch nicht schlecht.'},
   {na:'Hostia. Lukas merkt sich das Wort. Später fragt er María.'},
   {z:'Aquí están las llaves del piso.'},
   {z:'El agua caliente funciona... a veces. La caldera es muy vieja.',tr:'Das Warmwasser funktioniert... manchmal.'},
   {z:'Y nunca, NUNCA, tires papel al WC. Las tuberías son antiguas.',tr:'Wirf niemals Papier ins WC. Die Rohre sind alt.'},
   {z:'En la pared hay un cartel, escrito a mano con rotulador rojo:',tr:'An der Wand hängt ein Schild, handgeschrieben mit rotem Stift:'},
   {z:'NO ARROJAR PAPEL AL WC. ¡GRACIAS!',tr:'Kein Papier ins WC werfen. Danke!'},
   {na:'Mein erstes spanisches Schild. Auf einer Toilette. Sehr Madrid.'},
   {z:'¿Y tú qué estudias?'},
   {z:'Arquitectura. En la ETSAM.'},
   {z:'¡Hostia, qué chulo!',tr:'Mensch, wie cool!'},
   {z:'Yo soy ingeniera. Trabajo en una empresa de energías renovables.',tr:'Ich arbeite in einer Firma für erneuerbare Energien.'},
   {z:'En Galicia me llaman la rara porque me gusta el silencio.',tr:'In Galicien nennen sie mich die Seltsame, weil ich die Stille mag.'},
   {z:'Pablo es músico. Toca el cajón en los bares de Lavapiés.',tr:'Er spielt Cajón in den Bars von Lavapiés.'},
   {z:'María es periodista. Vivió dos años en Berlín.',tr:'Sie hat zwei Jahre in Berlin gelebt.'},
   {na:'Berlin. María kennt Berlin. Das merkt er sich.'},
   {z:'A las once, Lukas cierra los ojos un segundo. En la mesa.',tr:'Um elf schließt Lukas eine Sekunde lang die Augen. Am Tisch.'},
   {na:'María sieht es.'},
   {z:'Lukas, vete a dormir. Mañana hay más Madrid.',tr:'Lukas, geh schlafen. Morgen gibt es mehr Madrid.'},
   {z:'Buenas noches. Y gracias por la tortilla.',tr:'Und danke für die Tortilla.'},
   {z:'De nada, quillo. Mañana hago otra.',tr:'Nichts zu danken. Morgen mache ich noch eine.'},
   {na:'Er setzt sich aufs Bett. Es knarrt. Aus dem Koffer holt er ein gerahmtes Foto: seine Eltern vor der Haustür in Hamburg. Sein Vater hält einen Apfel, seine Mutter lacht.'},
   {z:'Goyo todavía duerme en la ventana de enfrente.',tr:'Goyo schläft immer noch am Fenster gegenüber.'},
   {na:'Egal, was in Madrid passiert, Goyo schläft.'},
   {na:'Im Bett hört er Geschirr, Marías leise Stimme, Pablos Lachen, irgendwo eine Tür. Geräusche, die nicht seine waren — und doch schon ein bisschen seine sind.'},
   {z:'Esto es mi casa. Por ahora.',tr:'Das ist mein Zuhause. Vorerst.'},
   {na:'Sein erster Satz, der direkt auf Spanisch entsteht.'}]},
 {level:'aufbau',n:3,title:'La tertulia',teaser:'Vier reden gleichzeitig — und Lukas sagt einen Satz, über den alle lachen.',body:[
   {na:'Eine Woche ist vergangen. Lukas kennt den Weg zum Bäcker und kann zwei Wörter verbinden, ohne im Kopf zu übersetzen.'},
   {z:'María lo invitó a una tertulia.',tr:'María lud ihn zu einer Tertulia ein.'},
   {na:'Eine Art Stammtisch unter Freunden. Immer dasselbe Café, einmal die Woche.'},
   {z:'Vente, alemán. Es informal. Solo hablar y beber cerveza.',tr:'Komm mit, Deutscher. Es ist informell. Nur reden und Bier trinken.'},
   {z:'Lukas dijo que sí. Delante del espejo, se preguntó por qué.',tr:'Lukas sagte ja. Vor dem Spiegel fragte er sich, warum.'},
   {z:'A las nueve fueron al Café Comercial, en la Glorieta de Bilbao.',tr:'Um neun gingen sie zum Café Comercial.'},
   {z:'El café existe desde 1887. Techos altos, espejos en las paredes, sillas de madera vieja.',tr:'Das Café gibt es seit 1887. Hohe Decken, Spiegel an den Wänden, alte Holzstühle.'},
   {na:'Älter als Coca-Cola, denkt Lukas.'},
   {z:'En una mesa redonda ya había tres personas.',tr:'An einem runden Tisch saßen schon drei Personen.'},
   {z:'Lukas conocía a una: Diego, profesor de historia, amigo de María.',tr:'Eine kannte Lukas: Diego, Geschichtslehrer, ein Freund von María.'},
   {z:'A los otros dos no los conocía.'},
   {z:'Mirad, este es Lukas. Es alemán, de Hamburgo. Está aquí para estudiar arquitectura.',tr:'Schaut, das ist Lukas. Er ist Deutscher, aus Hamburg. Er ist hier, um Architektur zu studieren.'},
   {z:'Tres hola a la vez. Tres voces distintas.',tr:'Drei Hallo gleichzeitig. Drei verschiedene Stimmen.'},
   {z:'Yo soy Bea. Mucho gusto.'},
   {na:'Ihre Augen sind hellgrün. Lukas merkt es, ohne es zu wollen.'},
   {z:'Yo soy Andrés. Bienvenido.'},
   {z:'En la mesa: cuatro botellas, un plato de aceitunas y otro de jamón.',tr:'Auf dem Tisch: vier Flaschen, ein Teller Oliven und einer mit Schinken.'},
   {z:'¿Qué os pongo?',tr:'Was bringe ich euch?'},
   {z:'Cuatro cañas más, por favor. Una para él.',tr:'Noch vier kleine Bier, bitte. Eines für ihn.'},
   {na:'Caña — ein kleines Bier vom Fass. Das hatte María ihm zu Hause erklärt.'},
   {z:'Brindaron. Lukas chocó demasiado flojo.',tr:'Sie stießen an. Lukas stieß zu schwach an.'},
   {z:'Más fuerte, alemán. En España chocamos fuerte.',tr:'Stärker, Deutscher. In Spanien stoßen wir fest an.'},
   {z:'Lukas repitió. Los vasos sonaron. Todos rieron.',tr:'Lukas wiederholte. Die Gläser klirrten. Alle lachten.'},
   {z:'Y entonces empezó lo que más miedo le daba: la conversación.',tr:'Und dann begann, wovor er die meiste Angst hatte: das Gespräch.'},
   {z:'Diego contaba algo. Bea lo interrumpía. Andrés comentaba y se reía. María contestaba.',tr:'Diego erzählte etwas. Bea unterbrach ihn. Andrés kommentierte und lachte. María antwortete.'},
   {z:'Lukas entendía palabras sueltas: fútbol, Atlético, árbitro.',tr:'Lukas verstand einzelne Wörter: Fußball, Atlético, Schiedsrichter.'},
   {na:'Alle reden gleichzeitig. In Hamburg redet immer nur einer. Hier drei, manchmal vier. Und niemand stört sich daran.'},
   {z:'Entendía el veinte por ciento. Quizá menos.',tr:'Er verstand zwanzig Prozent. Vielleicht weniger.'},
   {z:'Pero entendía una cosa: esta gente se quiere.',tr:'Aber eines verstand er: diese Leute mögen sich.'},
   {z:'Y tú, Lukas, ¿qué haces aquí en Madrid?',tr:'Und du, Lukas, was machst du hier in Madrid?'},
   {z:'Estudio arquitectura. Estoy aquí nueve meses. Empiezo el lunes.',tr:'Ich studiere Architektur. Ich bin neun Monate hier. Ich fange am Montag an.'},
   {z:'Ah, qué bien. ¿Y vienes solo? ¿Sin novia?',tr:'Ah, schön. Und du kommst allein? Ohne Freundin?'},
   {na:'Die Frage kommt direkter, als er erwartet hat.'},
   {z:'Sí. Vengo solo.'},
   {z:'Bea sonrió y no dijo nada más.',tr:'Bea lächelte und sagte nichts mehr.'},
   {z:'¿Y qué piensas de España hasta ahora?',tr:'Und was hältst du bisher von Spanien?'},
   {z:'Hay mucho ruido. Pero es bonito.',tr:'Es gibt viel Lärm. Aber es ist schön.'},
   {z:'¡Te has resumido España en cinco palabras!',tr:'Du hast Spanien in fünf Wörtern zusammengefasst!'},
   {na:'Alle lachen. Lukas lacht mit — und nicht aus Höflichkeit. Etwas, das er gesagt hat, war witzig. Sie lachen nicht über ihn.'},
   {z:'¡Por el ruido y por lo bonito! ¡Por Lukas!',tr:'Auf den Lärm und auf das Schöne! Auf Lukas!'},
   {z:'Brindaron otra vez. Lukas, esta vez, fuerte.',tr:'Sie stießen wieder an. Lukas diesmal fest.'},
   {z:'A veces entendía, a veces no. A veces empezaba una frase y se quedaba a mitad de camino.',tr:'Mal verstand er, mal nicht. Manchmal fing er einen Satz an und blieb auf halbem Weg stehen.'},
   {z:'María lo ayudaba en voz baja: sabes, no sabo. Tengo, no tieno.',tr:'María half ihm leise: sabes, nicht sabo. Tengo, nicht tieno.'},
   {z:'A medianoche estaba cansado, pero despierto por dentro.',tr:'Um Mitternacht war er müde, aber innerlich wach.'},
   {na:'Anders wach. Als hätte sein Gehirn vier Stunden lang Gewichte gehoben.'},
   {z:'¿Vienes la semana que viene?',tr:'Kommst du nächste Woche?'},
   {z:'Sí. Vengo.'},
   {z:'En el taxi, María le dijo: has hablado mucho, Lukas. Más de lo que crees.',tr:'Im Taxi sagte María: du hast viel gesprochen, Lukas. Mehr, als du glaubst.'},
   {z:'Las calles de Madrid estaban más vacías, pero nunca vacías del todo.',tr:'Die Straßen von Madrid waren leerer, aber nie ganz leer.'},
   {na:'Heute Abend habe ich mehr Spanisch gesprochen als in meinem ganzen Leben. Vielleicht waren es dreißig Sätze. Aber sie waren meine.'},
   {z:'En la cama, miró la ventana de enfrente. Goyo dormía. Como siempre.',tr:'Im Bett schaute er zum Fenster gegenüber. Goyo schlief. Wie immer.'},
   {z:'Bea tiene los ojos verdes.'},
   {na:'Sein erster spanischer Gedanke, der nichts mit Überleben zu tun hat.'}]},
 {level:'anwendung',n:4,title:'Un café en el barrio',teaser:'Allein an einer Theke — und die Frage, was ein cortado eigentlich ist.',body:[
   {p:'Sábado por la mañana, las nueve y media. María y Carmen todavía dormían, y Pablo no había vuelto a casa: algo con una chica, había insinuado María el jueves, con un giro de ojos que lo explicaba todo.'},
   {p:'Lukas tenía un plan pequeño pero importante: desayunar solo en un bar español. Sin María de traductora, sin Pablo repitiéndole el pedido tres veces. Solo él, una barra y su español.'},
   {p:'En la calle del Tribulete ya había ruido: niños jugando, un hombre descargando una furgoneta, alguien que gritaba desde un balcón. En Hamburgo, un sábado a esa hora, todavía habría silencio.'},
   {p:'Tres portales más allá, en la esquina, un cartel pequeño: BAR LOLA — DESDE 1972. Al lado, la foto descolorida de una mujer rubia con joyas de oro y una puerta con cortina de plástico. Lukas respiró hondo y entró.'},
   {p:'Dentro, el bar era estrecho y largo: barra de madera a la derecha, tres mesas a la izquierda, un mostrador de mosaico de los años setenta. Tres hombres mayores leían el periódico con la taza delante, y en la tele de la esquina repetían un partido de 2018.'},
   {p:'Detrás de la barra, la mujer de la foto —cincuenta años después, pero inconfundible— secaba vasos con un trapo. Pelo gris, labios rojos, gafas pequeñas sobre la nariz. Miró a Lukas sin sonreír.'},
   {p:'—Buenos días. —Buenos días —contestó él, y se sentó a dos taburetes del último señor, con la mochila en el suelo.'},
   {p:'Ella no preguntó nada más. Se quedó mirándolo con el trapo en la mano, esperando a que pidiera. Lukas había ensayado la frase en la cama, tres veces, tal como María se la había enseñado: no quiero, sino quería. Más suave. Más español.'},
   {p:'—Quería un café, por favor. Ella levantó las cejas y siguió esperando. —¿Qué café?'},
   {p:'Con eso no había contado. En Hamburgo hay café, y hay espresso. Aquí, por lo visto, había mucho más. La mujer señaló con la barbilla una pizarra en la pared: café solo, café con leche, cortado, americano, bombón, tostada con tomate, pincho de tortilla.'},
   {p:'¿Qué demonios era un cortado? Cortar significaba cortar. ¿Un café partido por la mitad? Lukas eligió lo seguro: —Un café con leche, por favor.'},
   {p:'Mientras la máquina soltaba vapor y todo el bar olía a café de verdad, el señor del Marca dijo, sin levantar la cabeza: —Lola, ¿me pones otro? —Que sí, hombre, que sí.'},
   {p:'Así que la mujer de detrás de la barra se llamaba Lola. Como el bar.'},
   {p:'Le puso delante una taza pequeña, un sobre de azúcar y una cucharilla. —¿Algo de comer? Tostada, pincho... —Una tostada con tomate, por favor. Y... ¿puedo preguntar una cosa?'},
   {p:'Lola lo miró de verdad por primera vez. Detrás de las gafas tenía los ojos grises, cansados pero despiertos. —Claro. Dime. —¿Qué es un cortado?'},
   {p:'Y entonces, por fin, sonrió. Poco, pero sonrió. —Un cortado es un café solo con un poquito de leche. Pequeño, como un espresso, pero cortado con leche. Por eso se llama así.'},
   {p:'—La próxima vez quiero un cortado, entonces. —Vale, alemán. La próxima vez, cortado.'},
   {p:'Alemán otra vez. Pero esta vez la palabra venía con un guiño.'},
   {p:'Lola volvió de la cocina con una rebanada de pan caliente, tomate triturado por encima, un vasito de aceite de oliva y un salero. Hizo un gesto con la mano: aceite, sal, así. Lukas la imitó y mordió.'},
   {p:'No era pan con tomate. Era otra cosa: caliente, salado, el aceite sabía a aceitunas de verdad y el tomate sabía a tomate. ¿Cómo había conseguido este país hacer tan bien algo tan sencillo?'},
   {p:'Mientras comía, en la barra empezó una conversación que aquellos hombres debían de haber tenido cien veces: el del Marca defendía al Atlético, el del País protestaba, el tercero no decía nada y Lola metía comentarios entre vaso y vaso. Lukas entendía un tercio, pero entendía algo más importante: aquel bar era su segundo salón, y Lola era a la vez su hija, su madre y su hermana.'},
   {p:'Cuando pidió la cuenta, Lola se acercó. —Café con leche y una tostada. Tres con cincuenta. Lukas le dio cinco euros, recogió el cambio y dejó cincuenta céntimos sobre la barra.'},
   {p:'Lola levantó una ceja. —¿Qué es eso? —Eh... para usted. Y entonces se rió, una risa entera y de verdad. —Alemán, en España la propina no se deja así. Pero gracias. Eres muy amable.'},
   {p:'Lukas se puso rojo. Los señores se rieron también, pero no de él, sino con él. El del Marca dijo, sin levantar la cabeza: —Es alemán. En Alemania son así. Y todos asintieron, como si eso lo explicara todo.'},
   {p:'Al llegar a la puerta, Lukas se dio la vuelta. —Hasta luego, Lola. —Hasta mañana, alemán.'},
   {p:'Hasta mañana. No hasta luego. Lola daba por hecho que volvería.'},
   {p:'En la calle, al sol, Lukas sonrió. Tenía el estómago caliente, el español un poco más firme y, por primera vez, un sitio en Madrid donde alguien conocía su apodo.'},
   {p:'Mañana, cortado.'}]}
  ];

  // ══ BUCH 2 · „Marta en Berlín" — Zielsprache de, Muttersprache es ══════════
  // Ziel-Anteil je Kapitel: 27 / 39 / 41 / 100 % (gemessen, Auftrag §3).
  var MARTA = [
 {level:'fundament',n:1,title:'Der Flughafen',teaser:'Marta aterriza en Berlín y nadie aplaude.',body:[
   {na:'Martes, las tres y veinte. El avión toca tierra en el aeropuerto BER. Cielo gris, hierba muy verde, edificios cuadrados y bajos.'},
   {na:'Y algo no pasa: nadie aplaude. En España aplaude medio pasaje. Aquí, silencio.'},
   {na:'Vale. Bienvenida a Alemania.'},
   {na:'Por los altavoces, una voz dice algo. Marta entiende dos palabras:'},
   {z:'Gepäckausgabe. Ausgang.',tr:'Recogida de equipajes. Salida.'},
   {na:'Seis meses de apps, doscientas palabras. Pero el alemán a velocidad real es otra cosa.'},
   {na:'Cinta número 7. Una maleta. No es la suya. Otra. Tampoco. Por fin, la maleta amarilla con su pegatina.'},
   {na:'Fuera, una ráfaga de aire frío. Septiembre en Berlín ya es otoño.'},
   {na:'En la cola de taxis, un hombre le hace una seña. Su taxi es un Mercedes. Por supuesto.'},
   {z:'Guten Tag. Wohin?',tr:'Buenas tardes. ¿A dónde?'},
   {z:'Oranienstraße 47. Kreuzberg, bitte.'},
   {z:'Kreuzberg. Alles klar. Ist das Ihr erstes Mal in Berlin?',tr:'Todo claro. ¿Es su primera vez en Berlín?'},
   {z:'Ja. Mein erstes Mal.'},
   {z:'Dann willkommen. Berlin ist groß, aber freundlich.',tr:'Pues bienvenida. Berlín es grande, pero amable.'},
   {z:'Breite Straßen, Straßenbahnen, überall Fahrräder. Viele Leute in Schwarz. Viel roter Backstein.',tr:'Calles anchas, tranvías, bicis por todas partes. Mucha gente de negro. Mucho ladrillo rojo.'},
   {z:'Woher kommen Sie?',tr:'¿De dónde viene usted?'},
   {z:'Ich komme aus Spanien. Aus Madrid.'},
   {z:'Ah, Madrid! Real Madrid. Sehr gut.'},
   {na:'Por supuesto. El fútbol. Es lo mismo en todas partes. Marta no lo sigue, pero asiente.'},
   {z:'Ja, ja. Real Madrid.'},
   {z:'Berlin ist schön. Aber kalt. Im Winter sehr kalt.',tr:'Berlín es bonito. Pero frío. En invierno, muy frío.'},
   {na:'Marta capta tres palabras y sonríe. El truco universal del extranjero: asentir y sonreír.'},
   {z:'Vierzig Minuten später hält das Taxi in Kreuzberg. Bäume, Balkone mit Pflanzen, große bunte Graffiti.',tr:'Cuarenta minutos después, el taxi para en Kreuzberg. Árboles, balcones con plantas, grafitis grandes y de colores.'},
   {na:'No es el Berlín de las postales. Le gusta más así.'},
   {z:'Achtundvierzig Euro fünfzig.',tr:'Cuarenta y ocho con cincuenta.'},
   {na:'Marta no entiende el número rápido. Mira la pantalla: 48,50 €. Da un billete de cincuenta y unas monedas.'},
   {z:'Willkommen in Berlin.',tr:'Bienvenida a Berlín.'},
   {z:'Danke schön. Und schönen Abend noch.',tr:'Muchas gracias. Y que tenga buena tarde.'},
   {na:'El taxi se va. Marta se queda sola en la acera con la maleta amarilla.'},
   {z:'Ein dunkles Holzportal, Nummer 47. Daneben viele Klingeln. Sie sucht den Namen: Becker, 3. Stock.',tr:'Un portal de madera oscura, número 47. Al lado, muchos timbres. Busca el nombre: Becker, 3er piso.'},
   {na:'Aprieta el timbre. Ahora empieza todo.'},
   {z:'Ja?'},
   {z:'Hallo... ich bin Marta.'},
   {z:'Marta! Endlich! Komm rauf, dritter Stock!',tr:'¡Marta! ¡Por fin! ¡Sube, tercer piso!'},
   {z:'Die Tür links. Ich mache schon auf.',tr:'La puerta de la izquierda. Ya te abro.'},
   {na:'El portal zumba. Dentro: olor a madera vieja, luces amarillas, escaleras grandes y elegantes.'},
   {na:'Los edificios de Berlín huelen distinto a los de Madrid. Ni mejor ni peor. Otro.'},
   {na:'Tres pisos. Con maleta. Marta sube despacio.'}]},

 {level:'fundament',n:2,title:'Meine neue WG',teaser:'Pan negro, tres quesos y un bávaro que dice Servus.',body:[
   {z:'Drinnen riecht es nach starkem Kaffee. Hohe Decken, ein Holzboden, der knarrt, ein Fahrrad an der Wand.',tr:'Dentro huele a café fuerte. Techos altos, un suelo de madera que cruje, una bici en la pared.'},
   {z:'Das ist der Flur. Hier links die Küche. Geradeaus das Wohnzimmer. Und hinten die Zimmer.',tr:'Este es el pasillo. A la izquierda la cocina. Recto el salón. Y al fondo las habitaciones.'},
   {na:'Marta capta tres palabras: Küche, Wohnzimmer, Zimmer. Lo demás se escapa. Sonríe y asiente. El truco universal, otra vez.'},
   {z:'In der Küche ist jemand.',tr:'En la cocina hay alguien.'},
   {z:'Ein Mann um die dreißig, blondes Haar, alte Jeans. Er schneidet ein dunkles, schweres Brot.',tr:'Un hombre de unos treinta, pelo rubio, vaqueros viejos. Corta un pan oscuro y pesado.'},
   {na:'Como un ladrillo.'},
   {z:'Servusss! Du musst die Marta sein! I bin der Felix!',tr:'¡Holaaa! ¡Tú debes de ser Marta! ¡Yo soy Felix!'},
   {na:'Servus? I bin? Marta ha estudiado Hallo, no Servus. Y ich bin, no i bin. Aquí pasa algo raro.'},
   {z:'Er kommt aus Bayern. Aus München. Er spricht ein bisschen anders.',tr:'Viene de Baviera. De Múnich. Habla un poco diferente.'},
   {z:'Hallo, Felix. Ich bin Marta. Ich bin aus Madrid.'},
   {z:'Madrid! Olé! Ich liebe Madrid. Sangría, paella, Fiesta!'},
   {na:'El mismo cliché en todas partes. Pero lo dice con tanto entusiasmo que es difícil enfadarse.'},
   {z:'Jetzt kommt noch jemand ins Zimmer.',tr:'Ahora entra alguien más en la habitación.'},
   {z:'Eine Frau, Ende dreißig, kurzes braunes Haar, runde Brille. Sie geht sehr ruhig.',tr:'Una mujer de casi cuarenta, pelo castaño corto, gafas redondas. Camina muy tranquila.'},
   {z:'Hallo. Ich bin Anna. Willkommen.'},
   {na:'Tres palabras. Voz baja. Una sonrisa pequeña pero verdadera.'},
   {na:'Anna es lo opuesto a Felix. Y los dos son alemanes.'},
   {z:'Anna kommt aus Hamburg. Sie ist Ingenieurin. Felix ist Musiker.',tr:'Anna viene de Hamburgo. Es ingeniera. Felix es músico.'},
   {na:'Norte y sur. Silencio y ruido. Y aquí viven juntos, aparentemente sin matarse.'},
   {z:'Komm, wir essen jetzt was. Du hast bestimmt Hunger nach dem Flug.',tr:'Ven, vamos a comer algo. Seguro que tienes hambre después del vuelo.'},
   {z:'Auf dem Tisch stehen Brot, Käse, Butter, Wurst, Gurken und vier Flaschen Bier.',tr:'Sobre la mesa hay pan, queso, mantequilla, embutido, pepinillos y cuatro botellas de cerveza.'},
   {na:'¿Esto es la cena? ¿No hay nada caliente?'},
   {z:'In Deutschland heißt das Abendbrot. Kein warmes Essen. Nur Brot, Käse, ein bisschen Fleisch. Und Bier, natürlich.',tr:'En Alemania se llama Abendbrot. Sin comida caliente. Solo pan, queso, un poco de carne. Y cerveza, claro.'},
   {na:'Abendbrot. Pan-de-la-tarde. Cena fría. Vale. Mente abierta.'},
   {z:'Magst du Bier?',tr:'¿Te gusta la cerveza?'},
   {z:'Ja. Danke.'},
   {z:'Prost! Auf Marta!',tr:'¡Salud! ¡Por Marta!'},
   {z:'Marta schaut jedem in die Augen, während die Flaschen sich treffen.',tr:'Marta mira a los ojos de cada uno mientras chocan las botellas.'},
   {na:'Lo leyó en un blog: si no miras a los ojos al brindar, son siete años de mala suerte en la cama. Marta no se arriesga.'},
   {z:'Sehr gut! Du schaust in die Augen. Du bist keine Touristin.',tr:'¡Muy bien! Miras a los ojos. No eres una turista.'},
   {na:'Cinco minutos en Berlín y ya he hecho algo bien.'},
   {z:'Das Brot ist dunkel und schwer. Es schmeckt nach Körnern und Kruste.',tr:'El pan es oscuro y pesado. Sabe a semillas y a corteza.'},
   {na:'No es el pan blanco español. Es un alimento de verdad, no un acompañamiento.'},
   {z:'Ein Käse ist sehr stark, fast scharf. Der zweite ist weich. Der dritte hat kleine Löcher.',tr:'Un queso es muy fuerte, casi pica. El segundo es suave. El tercero tiene agujeros pequeños.'},
   {na:'Nosotros tenemos manchego. Ellos, veintisiete quesos en una sola cena.'},
   {z:'Wo wohnst du in Madrid?',tr:'¿Dónde vives en Madrid?'},
   {z:'Ich wohne in Madrid. In... eh... cerca del centro.'},
   {z:'In der Nähe vom Zentrum.',tr:'Cerca del centro.'},
   {z:'In der Nähe vom Zentrum. Danke.'},
   {na:'Anna asiente y no dice nada más. Felix le enseñará las palabras divertidas, Jonas las prácticas. Anna, la lengua exacta.'},
   {z:'Du bist müde. Komm, ich zeige dir dein Zimmer.',tr:'Estás cansada. Ven, te enseño tu habitación.'},
   {z:'Gute Nacht. Danke für alles.'},
   {z:'Das Zimmer ist klein: ein Bett, ein Schreibtisch unter dem Fenster, ein Schrank von IKEA.',tr:'La habitación es pequeña: una cama, un escritorio bajo la ventana, un armario de IKEA.'},
   {na:'En Alemania también hay IKEA, por lo visto. Pero la ventana da a un patio con árboles de verdad. En Madrid veía un muro.'},
   {z:'Marta legt sich auf die Decke, ohne sich auszuziehen. Nur fünf Minuten, denkt sie.',tr:'Marta se tumba sobre la colcha sin desvestirse. Solo cinco minutos, piensa.'},
   {na:'Se duerme en treinta segundos.'},
   {z:'In der Küche macht Felix noch eine Flasche auf.',tr:'En la cocina, Felix abre otra botella.'},
   {z:'Sie ist nett, oder?',tr:'Es maja, ¿verdad?'},
   {z:'Ja. Sehr.'},
   {z:'Sie wird Berlin mögen.',tr:'A Marta le va a gustar Berlín.'},
   {na:'Y por alguna razón, los tres saben que Anna tiene razón.'}]},

 {level:'aufbau',n:3,title:'Der Stammtisch',teaser:'Cincuenta segundos de silencio — y nadie se muere.',body:[
   {na:'Jueves. Una semana en Berlín.'},
   {z:'Marta kannte jetzt die Straßen von Kreuzberg: die Bäckerei an der Ecke, den Supermarkt, den Kiosk mit der spanischen Wochenzeitung, die außer ihr niemand las.',tr:'Marta conocía ya las calles de Kreuzberg: la panadería de la esquina, el supermercado, el quiosco con el semanario español que no leía nadie excepto ella.'},
   {na:'Pequeños anclajes en una ciudad que todavía no se ha vuelto suya.'},
   {z:'Marta, kommst du mit? Wir gehen zum Stammtisch.',tr:'Marta, ¿vienes? Vamos al Stammtisch.'},
   {z:'Stammtisch: Stamm ist der Stamm eines Baumes, auch eine Gruppe. Tisch ist der Tisch. Der Tisch der Gruppe.',tr:'Stammtisch: Stamm es el tronco de un árbol, también un grupo. Tisch es la mesa. La mesa del grupo.'},
   {z:'Es ist immer derselbe Tisch, immer derselbe Tag, immer dieselben Leute. Niemand sonst darf sich an diesen Tisch setzen.',tr:'Es siempre la misma mesa, siempre el mismo día, siempre la misma gente. Nadie más puede sentarse a esa mesa.'},
   {na:'Como la tertulia española. Pero al revés.'},
   {z:'Anna kommt nicht mit?',tr:'¿Anna no viene?'},
   {z:'Nein, heute nicht. Viel Spaß.',tr:'No, hoy no. Que os divirtáis.'},
   {na:'Anna no va a los Stammtische. Marta lo entiende sin explicación. Anna escoge.'},
   {z:'Sie gingen zehn Minuten zu Fuß. Es war schon fast dunkel, obwohl es erst sieben war.',tr:'Anduvieron diez minutos. Ya era casi de noche, aunque solo eran las siete.'},
   {z:'Die Kneipe hieß Zum Goldenen Anker. Dunkles Holz, gelbes Licht, der Geruch von Bier und altem Holz.',tr:'La taberna se llamaba Al Ancla Dorada. Madera oscura, luz amarilla, olor a cerveza y madera vieja.'},
   {z:'Jonas grüßte den Kellner mit einem Nicken. Der Kellner nickte zurück. Kein Wort.',tr:'Jonas saludó al camarero con un gesto de cabeza. El camarero se lo devolvió. Ni una palabra.'},
   {na:'En España serían diez segundos de besos y ¿qué tal, Pepe? Aquí, un cabeceo. Y ya.'},
   {z:'Auf dem runden Tisch war ein Metallschild festgeschraubt: Stammtisch Die Donnerstagsfreunde, seit 1987.',tr:'En la mesa redonda había una placa metálica atornillada: Stammtisch Los Amigos del Jueves, desde 1987.'},
   {na:'Treinta y nueve años. Yo todavía no había nacido.'},
   {z:'Marta, das ist Herr Weber, er ist Lehrer. Frau Schmidt ist Journalistin. Und das ist Tom, er studiert Geschichte.',tr:'Marta, este es el señor Weber, es profesor. La señora Schmidt es periodista. Y este es Tom, estudia historia.'},
   {z:'Hallo. Ich bin Marta. Ich komme aus Madrid.'},
   {z:'Drei Nicken. Drei kleine Lächeln. Und dann keine einzige Nachfrage.',tr:'Tres asentimientos. Tres sonrisas pequeñas. Y después ni una sola pregunta.'},
   {na:'Nadie dice ¡ah, Madrid, qué bien! Nadie pregunta ¿y por qué viniste? Solo silencio.'},
   {z:'Fünf Bier. Fünf leise Danke. Marta schaute jedem in die Augen und sagte Prost.',tr:'Cinco cervezas. Cinco gracias en voz baja. Marta miró a los ojos de cada uno y dijo Prost.'},
   {z:'Und dann passierte nichts. Dreißig Sekunden. Vierzig. Fünfzig Sekunden Stille.',tr:'Y entonces no pasó nada. Treinta segundos. Cuarenta. Cincuenta segundos de silencio.'},
   {z:'Herr Weber blätterte um. Frau Schmidt schrieb etwas. Tom drehte einen Bierdeckel. Felix schaute zufrieden an die Decke.',tr:'El señor Weber pasó una página. La señora Schmidt escribió algo. Tom daba vueltas a un posavasos. Felix miraba al techo, satisfecho.'},
   {na:'¿He hecho algo mal? ¿Los estoy aburriendo? En España alguien ya estaría preguntando por mi familia, por mi novio, por todo.'},
   {z:'Magst du Berlin bisher?',tr:'¿Te gusta Berlín hasta ahora?'},
   {z:'Ja. Es ist anders als Madrid. Aber ich mag es.'},
   {z:'Frau Schmidt nickte, lächelte kurz und schrieb weiter. Sie brauchte nicht mehr.',tr:'La señora Schmidt asintió, sonrió brevemente y siguió escribiendo. No necesitaba más.'},
   {na:'Su pregunta era real, no rellena-silencio. Aquí no se habla para llenar el aire. Se habla cuando se tiene algo que decir.'},
   {z:'Noch eine Stille. Aber diesmal schwitzte Marta nicht.',tr:'Otro silencio. Pero esta vez Marta no sudó.'},
   {z:'Tom fragte Jonas etwas über einen Film. Felix unterbrach mit einer sehr starken Meinung. Drei Minuten Gespräch. Dann wieder Stille. Bequeme Stille.',tr:'Tom preguntó a Jonas algo sobre una película. Felix interrumpió con una opinión muy fuerte. Tres minutos de conversación. Después, otra vez silencio. Silencio cómodo.'},
   {na:'Como una respiración. Inhalar, exhalar. Hablar, callar.'},
   {z:'Ich muss gehen. Meine Frau wartet.',tr:'Tengo que irme. Mi mujer está esperando.'},
   {z:'Um zehn stand auch Frau Schmidt auf und sagte Auf Wiedersehen.',tr:'A las diez, la señora Schmidt se levantó también y dijo Auf Wiedersehen.'},
   {z:'Ohne die Älteren am Tisch wurde das Gespräch schneller, lauter, lustiger.',tr:'Sin los mayores en la mesa, la conversación se volvió más rápida, más alta, más divertida.'},
   {z:'Stimmt es, dass in Spanien die Siesta Pflicht ist? Esst ihr jeden Tag Paella?',tr:'¿Es verdad que en España la siesta es obligatoria? ¿Coméis paella todos los días?'},
   {z:'Wenn Marta ein Wort suchte, wartete Tom. Er füllte die Lücke nicht. Und wenn sie es fand, nickte er.',tr:'Cuando Marta buscaba una palabra, Tom esperaba. No rellenaba el hueco. Y cuando la encontraba, asentía.'},
   {na:'Tom escucha como Anna. Pero más cálido. Más curioso.'},
   {z:'Ich kann nicht mehr. Ich muss schlafen.',tr:'No puedo más. Tengo que dormir.'},
   {z:'Jeder zahlte genau das Seine.',tr:'Cada uno pagó exactamente lo suyo.'},
   {na:'En España pagaríamos a turnos, nos invitaríamos. Aquí, cada uno lo suyo. Y nadie lo vive como falta de generosidad.'},
   {z:'An einer Ecke blieb Tom stehen und schaute Marta direkt an.',tr:'En una esquina, Tom se detuvo y miró a Marta directamente.'},
   {z:'Marta, möchtest du nächste Woche einen Kaffee trinken? Mit mir?',tr:'Marta, ¿quieres tomar un café la próxima semana? ¿Conmigo?'},
   {na:'Una invitación. Directa. Sin rodeos. Muy alemana. Pero muy clara.'},
   {z:'Ja. Gerne.'},
   {z:'Bis dann.'},
   {z:'Felix gab ihr einen kleinen Stoß an die Schulter. Jonas lächelte, ohne sie anzusehen.',tr:'Felix le dio un golpecito en el hombro. Jonas sonrió sin mirarla.'},
   {na:'Hoy he aprendido algo: el silencio alemán no está vacío. Es un espacio. Y dentro caben muchas cosas, incluso una invitación a un café.'},
   {z:'Tom hat sehr dunkle Augen. Sehr ernst. Aber wenn er lächelt, lächelt er ganz.'},
   {na:'Su primera observación afectiva en su nueva vida.'}]},

 {level:'anwendung',n:4,title:'In der Bäckerei',teaser:'Dreißig Sorten Brötchen — und eine Frau, die sich Gesichter merkt.',body:[
   {p:'Sonntagmorgen, halb neun. Die Wohnung war still. Felix schlief, Jonas war bei Freunden in Prenzlauer Berg, und Anna war laufen gegangen, wie jeden Morgen um halb acht, auch im Winter.'},
   {p:'Marta hatte Hunger und einen Plan: allein in die Bäckerei gehen. Ohne Jonas als Übersetzer, ohne Felix als Anfeuerer. Nur sie, ihre zehn angesammelten Tage Deutsch und ein Berliner Bäcker, der vermutlich keine Zeit für Gestotter hatte.'},
   {p:'Ich gehe in die Bäckerei. Ich bestelle etwas. Ich bezahle. Ich gehe wieder raus. Vier Handlungen. Das schaffe ich.'},
   {p:'Draußen war Berlin am Sonntag eine andere Stadt: leiser, fast ohne Autos, Paare mit Hunden, langsame Radfahrer. In Madrid wären die Terrassen um diese Zeit schon voll. Hier atmete die Stadt.'},
   {p:'Drei Straßen weiter, an der Ecke zur Skalitzer Straße, lag die Bäckerei, an der sie jeden Tag vorbeiging und die sie noch nie betreten hatte. Eine schmale, dunkelgrün gestrichene Fassade, ein handgemaltes Schild: BÄCKEREI SCHULTZ — seit 1962. Im Schaufenster Körbe voller Brot, ein angeschnittener Apfelkuchen, kleine Pappschilder mit handgeschriebenen Preisen.'},
   {p:'Marta drückte die Tür auf. Eine Glocke klingelte. Drinnen der sofortige, mächtige Geruch von frisch gebackenem Brot — der Geruch, der einen Hunger weckt, von dem man nichts gewusst hatte.'},
   {p:'Der Laden war klein: Glasvitrinen rechts, eine alte Registrierkasse links, Regale mit Kaffee und Marmelade im Hintergrund. Vor ihr standen schon drei Leute. Marta stellte sich hinten an und beobachtete. Erst schauen, dann sprechen — Regel Nummer eins für Ausländer.'},
   {p:'Hinter dem Tresen stand eine Frau von etwa fünfundsechzig Jahren. Kurzes Haar, weiß mit einem blonden Rest, eine kleine Brille auf der Nasenspitze, eine weiße Schürze mit grün gesticktem Logo. Schnelle Hände. Für jeden Kunden ein kurzes, aber echtes Lächeln.'},
   {p:'Die erste Kundin bestellte etwas sehr Schnelles. Marta verstand nur drei Brötchen und ein Vollkornbrot. Bezahlen, Wechselgeld, schönen Sonntag, weg. Der zweite Kunde war noch schneller. Die dritte, eine Frau in Martas Alter, nahm einen Kaffee zum Mitnehmen und ein Croissant. Croissant verstand sie — Croissant ist international, Gott sei Dank.'},
   {p:'Und plötzlich war sie dran. Die Frau hob den Blick über die kleine Brille hinweg.'},
   {p:'—Was darf es sein?'},
   {p:'Marta verstand den Satz nicht genau, aber sie verstand die Frage. Sie schaute in die Vitrine und erstarrte. So viele Brote. So viele Brötchen. Runde, längliche, mit Körnern, mit Mehl bestäubt, manche fast schwarz, manche fast weiß. Ich kenne die Namen nicht. Ich weiß nicht, was ich will.'},
   {p:'Sie zeigte mit dem Finger auf ein rundes Brötchen mit Sesam. —Äh... das, bitte. Und das. Und das.'},
   {p:'Frau Schultz nahm die drei mit der Zange und legte sie in eine braune Papiertüte. —Sonst noch was?'},
   {p:'Und hier tat Marta etwas, das sie nicht geplant hatte. Etwas Mutiges. Etwas, das sie in Madrid ohne Nachdenken täte, das aber auf Deutsch Kraft kostete. Sie stellte eine Frage.'},
   {p:'—Entschuldigung... was ist das?'},
   {p:'Frau Schultz schaute hin. Eine Pause. Und dann ihr erstes vollständiges Lächeln. —Das ist ein Sesambrötchen. Mit Sesam. Sehr lecker mit Käse.'},
   {p:'—Sesambrötchen, wiederholte Marta langsam. —Genau.'},
   {p:'Und dann, weil Berliner Bäckerinnen manchmal Zeit haben, wenn eine Kundin es verdient, zeigte Frau Schultz auf die anderen beiden. —Das ist ein Mohnbrötchen. Und das hier ist ein Roggenbrötchen. Aus Roggen. Etwas dunkler. Sehr deutsch.'},
   {p:'Marta wiederholte jedes Wort, und ihr Gehirn legte sie ab wie ein Kind, das zum ersten Mal die Namen der Dinge bekommt.'},
   {p:'—Bist du neu hier? —Ja. Ich komme aus Spanien. Aus Madrid. Ich bin hier neun Monate.'},
   {p:'—Madrid. Schön. Ich war einmal in Madrid, vor vielen Jahren. Sehr heiß.'},
   {p:'Eine Berlinerin, die vor Jahrzehnten in Madrid war und sich an die Hitze erinnert. Hinter Marta räusperte sich jemand leise — kleiner Berliner Druck. Frau Schultz kehrte zur normalen Geschwindigkeit zurück. —Drei Brötchen. Zwei Euro zehn.'},
   {p:'Marta zahlte mit einem Fünfer. Und dann nahm Frau Schultz ein viertes Brötchen aus der Vitrine und legte es dazu.'},
   {p:'—Das ist ein Käsebrötchen. Mit Käse oben. Probier mal. Geschenk.'},
   {p:'Geschenk. Marta wusste nicht, was sie sagen sollte. Frau Schultz hatte ihr, ohne es zu wissen, gerade einen Anker im Viertel gegeben.'},
   {p:'—Vielen Dank. Vielen, vielen Dank. Frau Schultz machte eine kleine Handbewegung, die nichts zu danken hieß. —Komm wieder.'},
   {p:'Draußen klingelte die Glocke noch einmal. Die Papiertüte war warm in ihren Händen, weil die Brötchen frisch aus dem Ofen kamen. Marta ging langsam nach Hause — langsam, weil gerade etwas Gutes passiert war und sie nicht wollte, dass es endete.'},
   {p:'Im Hausflur, bevor sie hochging, öffnete sie die Tüte, nahm das Käsebrötchen heraus und biss hinein, ohne auf die Wohnung zu warten. Es war gut. Wirklich gut. Kein Käse und Brot, sondern kräftiger Käse, außen knusprig, innen weich. Eine einfache Sache, sehr gut gemacht.'},
   {p:'In der Küche legte sie die Brötchen in einen Korb, machte Kaffee, holte Butter und Marmelade und frühstückte allein am Fenster.'},
   {p:'Anna kam vom Laufen zurück, als Marta beim zweiten Kaffee war. Sie sah den Korb und lächelte. —Du warst bei Frau Schultz. —Ja. Allein. Mein erstes Mal.'},
   {p:'Anna goss sich Kaffee ein, nahm ein Brötchen und strich Butter darauf. —Sie ist eine gute Frau. Sie merkt sich Gesichter.'},
   {p:'Und Marta verstand, dass dieser Satz ein Segen war. Eine Frau, die sich mein Gesicht merkt, in einer Stadt, die mich noch nicht kennt.'},
   {p:'An diesem Abend schrieb Marta vier Wörter in das Heft, in dem sie ihr neues Deutsch sammelte: Sesambrötchen, Mohnbrötchen, Roggenbrötchen, Käsebrötchen — Geschenk. Und darunter, auf Spanisch, eine persönliche Notiz: Frau Schultz se acuerda de mi cara.'}]}
  ];

  // ── Die Bücher. Ein neues Sprachpaar = ein weiterer Eintrag. ──
  var BUECHER = [
    { buch: 'lukas-madrid', zielsprache: 'es', muttersprache: 'de',
      titel: 'Lukas in Madrid', kapitel: LUKAS },
    { buch: 'marta-berlin', zielsprache: 'de', muttersprache: 'es',
      titel: 'Marta en Berlín', kapitel: MARTA }
  ].map(function (b) {
    b.etappen = etappenFuer(b.muttersprache);
    return b;
  });

  // ── Öffentlich: Buch zum Sprachpaar oder null (nie werfen, nie erfinden). ──
  w.spikiuLearnroman = function (zielsprache, muttersprache) {
    var ziel = zielsprache || '', mutter = muttersprache || '';
    for (var i = 0; i < BUECHER.length; i++) {
      if (BUECHER[i].zielsprache === ziel && BUECHER[i].muttersprache === mutter) return BUECHER[i];
    }
    return null;
  };
  // Reihenfolge/IDs der Etappen für die Freischaltung im Raum.
  w.spikiuLearnroman.etappenIds = ETAPPEN_IDS.slice();
  // Welche Sprachpaare gibt es überhaupt? (für einen ehrlichen leeren Zustand)
  w.spikiuLearnroman.paare = BUECHER.map(function (b) {
    return { zielsprache: b.zielsprache, muttersprache: b.muttersprache, titel: b.titel };
  });

})(window);
